language: python 
python: 
- "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"  
before_install: 
- cd decide
install: 
- pip install -r ../requirements.txt
before_script:
- cp local_settings.travis.py local_settings.py
- python manage.py migrate
script: 
- python manage.py test